caffeine.jcache {
  default {
    policy.maximum.size = 500
  }

  # Hibernate framework cache holding the cached query results
  default-query-results-region {}

  # Hibernate framework's update-timestamps region must not be bounded; evicting a timestamp
  # would break the query cache's staleness detection
  default-update-timestamps-region {
    policy.maximum.size = null
  }

  # Hibernate application caches
  com.github.benmanes.caffeine.examples.hibernate.User {}
  com.github.benmanes.caffeine.examples.hibernate.Skill {}
  com.github.benmanes.caffeine.examples.hibernate.Project {}
}
