name: Bearer
permissions: {}
on: [ push, pull_request, workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  bearer:
    name: Bearer
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read # Needed for uploading security scan results
      security-events: write # Needed for uploading security scan results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@6c3c2f2c1c457b00c10c4848d6f5491db3b629df # v2.18.0
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.cycode.com:443
            api.github.com:443
            github.com:443
            raw.githubusercontent.com:443
            release-assets.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Bearer
        uses: bearer/bearer-action@828eeb928ce2f4a7ca5ed57fb8b59508cb8c79bc # v2
        continue-on-error: true
        with:
          format: sarif
          output: results.sarif
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: results.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@95e58e9a2cdfd71adc6e0353d5c52f41a045d225 # v4.35.2
        if: steps.check_files.outputs.files_exists == 'true'
        with:
          sarif_file: results.sarif
