name: Codacy
permissions: {}
on: [ push, pull_request, workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    timeout-minutes: 15
    permissions:
      contents: read
      actions: read # Needed for uploading security scan results
      security-events: write # Needed for uploading security scan results
    if: github.event.repository.fork == false
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          disable-sudo-and-containers: false
          egress-policy: block
          allowed-endpoints: >
            api.codacy.com:443
            api.github.com:443
            auth.docker.io:443
            github.com:443
            golang.org:443
            objects.githubusercontent.com:443
            production.cloudflare.docker.com:443
            raw.githubusercontent.com:443
            registry-1.docker.io:443
            *.blob.core.windows.net:443
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Run Codacy Analysis
        uses: codacy/codacy-analysis-cli-action@562ee3e92b8e92df8b67e0a5ff8aa8e261919c08 # v4.4.7
        continue-on-error: true
        with:
          format: sarif
          output: /tmp/results.sarif
          gh-code-scanning-compat: true
          max-allowed-issues: 2147483647
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: /tmp/results.sarif
      - name: Remove duplicate runs
        if: steps.check_files.outputs.files_exists == 'true'
        run: jq -c '.runs |= unique_by({tool, invocations, results})' < /tmp/results.sarif > codacy.sarif
      - name: Upload Reports
        if: steps.check_files.outputs.files_exists == 'true'
        uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
        with:
          retention-days: 1
          name: SARIF file
          path: codacy.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@c10b8064de6f491fea524254123dbe5e09572f13 # v4.35.1
        if: steps.check_files.outputs.files_exists == 'true'
        continue-on-error: true
        with:
          sarif_file: codacy.sarif
