name: Submit dependency graph (pull request)
permissions: {}
on:
  workflow_run:
    workflows: ['Generate dependency graph (pull request)']
    types: [completed]
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  JAVA_VERSION: 25

jobs:
  submit-dependency-graph:
    name: Submit Dependency Graph
    runs-on: ubuntu-latest
    permissions:
      contents: write # Needed for submitting the dependency graph
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@f808768d1510423e83855289c910610ca9b43176 # v2.17.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.adoptium.net:443
            api.github.com:443
            caffeine.develocity.cloud:443
            downloads.gradle.org:443
            downloads.gradle-dn.com:443
            github.com:443
            objects.githubusercontent.com:443
            plugins.gradle.org:443
            plugins-artifacts.gradle.org:443
            repo.maven.apache.org:443
            repo1.maven.org:443
            services.gradle.org:443
      - name: Retrieve and submit dependency graph
        uses: gradle/actions/dependency-submission@50e97c2cd7a37755bbfafc9c5b7cafaece252f6e # v6.1.0
        with:
          dependency-graph: download-and-submit
