name: Early Access JDK Tests
permissions: {}
on:
  schedule:
    - cron: '0 0 * * 5'
  workflow_dispatch: {}
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
env:
  DEVELOCITY_ACCESS_KEY: ${{ secrets.DEVELOCITY_ACCESS_KEY }}
  ALLOWED_ENDPOINTS: >
    *.actions.githubusercontent.com:443
    api.adoptium.net:443
    api.foojay.io:443
    api.github.com:443
    caffeine.gradle-enterprise.cloud:443
    download.java.net:443
    download.oracle.com:443
    downloads.gradle.org:443
    downloads.gradle-dn.com:443
    gds.oracle.com:443
    ghcr.io:443
    github.com:443
    jdk.java.net:443
    objects.githubusercontent.com:443
    oss.sonatype.org:443
    plugins.gradle.org:443
    plugins-artifacts.gradle.org:443
    raw.githubusercontent.com:443
    repo.gradle.org:443
    repo.maven.apache.org:443
    repo1.maven.org:443
    scans-in.gradle.com:443
    services.gradle.org:443

jobs:
  tests:
    name: Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        suite:
          - weakKeysAndStrongValuesStatsAsyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsAsyncManualUnboundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncLoadingUnboundedCaffeineSlowTest
          - strongKeysAndSoftValuesStatsSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsAsyncLoadingBoundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualUnboundedCaffeineSlowTest
          - strongKeysAndStrongValuesStatsAsyncLoadingUnboundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsAsyncManualBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncLoadingUnboundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncLoadingBoundedCaffeineSlowTest
          - strongKeysAndStrongValuesStatsSyncLoadingUnboundedCaffeineTest
          - strongKeysAndStrongValuesStatsAsyncManualUnboundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualBoundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsAsyncLoadingUnboundedCaffeineTest
          - weakKeysAndSoftValuesStatsSyncManualUnboundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualBoundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncLoadingUnboundedGuavaSlowTest
          - strongKeysAndStrongValuesStatsSyncManualUnboundedCaffeineTest
          - strongKeysAndStrongValuesStatsAsyncLoadingBoundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncManualBoundedCaffeineSlowTest
          - strongKeysAndSoftValuesStatsSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualUnboundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsSyncLoadingUnboundedCaffeineTest
          - weakKeysAndStrongValuesStatsAsyncManualUnboundedCaffeineTest
          - weakKeysAndStrongValuesAsyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncLoadingBoundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualUnboundedGuavaSlowTest
          - strongKeysAndWeakValuesStatsSyncLoadingUnboundedCaffeineTest
          - strongKeysAndStrongValuesStatsSyncLoadingBoundedCaffeineTest
          - strongKeysAndStrongValuesStatsAsyncManualBoundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncManualUnboundedGuavaSlowTest
          - strongKeysAndSoftValuesStatsSyncLoadingUnboundedCaffeineTest
          - weakKeysAndWeakValuesStatsSyncManualBoundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndStrongValuesSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualUnboundedCaffeineTest
          - weakKeysAndStrongValuesStatsSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsAsyncLoadingBoundedCaffeineTest
          - weakKeysAndStrongValuesAsyncManualUnboundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncManualBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncLoadingUnboundedGuavaSlowTest
          - strongKeysAndWeakValuesSyncLoadingUnboundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualUnboundedCaffeineTest
          - strongKeysAndWeakValuesStatsSyncLoadingBoundedGuavaSlowTest
          - strongKeysAndStrongValuesStatsSyncManualBoundedCaffeineTest
          - strongKeysAndStrongValuesStatsSyncLoadingUnboundedGuavaTest
          - strongKeysAndSoftValuesSyncLoadingUnboundedCaffeineSlowTest
          - strongKeysAndSoftValuesStatsSyncManualUnboundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncManualUnboundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncLoadingUnboundedCaffeineTest
          - weakKeysAndStrongValuesSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualBoundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsSyncLoadingBoundedCaffeineTest
          - weakKeysAndStrongValuesStatsAsyncManualBoundedCaffeineTest
          - weakKeysAndStrongValuesAsyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncManualUnboundedGuavaSlowTest
          - weakKeysAndSoftValuesStatsSyncLoadingUnboundedCaffeineTest
          - strongKeysAndWeakValuesSyncManualUnboundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualBoundedGuavaSlowTest
          - strongKeysAndWeakValuesStatsSyncLoadingBoundedCaffeineTest
          - strongKeysAndStrongValuesStatsSyncManualUnboundedGuavaTest
          - strongKeysAndStrongValuesAsyncLoadingUnboundedCaffeineTest
          - strongKeysAndSoftValuesSyncManualUnboundedCaffeineSlowTest
          - strongKeysAndSoftValuesStatsSyncManualBoundedGuavaSlowTest
          - strongKeysAndSoftValuesStatsSyncLoadingBoundedCaffeineTest
          - weakKeysAndWeakValuesSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncManualUnboundedCaffeineTest
          - weakKeysAndWeakValuesStatsSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndStrongValuesSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndStrongValuesStatsSyncManualBoundedCaffeineTest
          - weakKeysAndStrongValuesStatsSyncLoadingUnboundedGuavaTest
          - weakKeysAndStrongValuesAsyncManualBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesSyncLoadingUnboundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncManualUnboundedCaffeineTest
          - weakKeysAndSoftValuesStatsSyncLoadingBoundedGuavaSlowTest
          - strongKeysAndWeakValuesSyncLoadingBoundedCaffeineSlowTest
          - strongKeysAndWeakValuesStatsSyncManualBoundedCaffeineTest
          - strongKeysAndWeakValuesStatsSyncLoadingUnboundedGuavaTest
          - strongKeysAndStrongValuesSyncLoadingUnboundedCaffeineTest
          - strongKeysAndStrongValuesStatsSyncLoadingBoundedGuavaTest
          - strongKeysAndStrongValuesAsyncManualUnboundedCaffeineTest
          - strongKeysAndSoftValuesSyncLoadingBoundedCaffeineSlowTest
          - strongKeysAndSoftValuesStatsSyncManualBoundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncLoadingUnboundedGuavaTest
          - weakKeysAndWeakValuesSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncManualBoundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncLoadingBoundedCaffeineTest
          - weakKeysAndStrongValuesSyncManualBoundedCaffeineSlowTest
          - weakKeysAndStrongValuesSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsSyncManualUnboundedGuavaTest
          - weakKeysAndStrongValuesAsyncLoadingUnboundedCaffeineTest
          - weakKeysAndSoftValuesSyncManualUnboundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncManualBoundedGuavaSlowTest
          - weakKeysAndSoftValuesStatsSyncLoadingBoundedCaffeineTest
          - strongKeysAndWeakValuesSyncManualBoundedCaffeineSlowTest
          - strongKeysAndWeakValuesSyncLoadingUnboundedGuavaSlowTest
          - strongKeysAndWeakValuesStatsSyncManualUnboundedGuavaTest
          - strongKeysAndStrongValuesSyncManualUnboundedCaffeineTest
          - strongKeysAndStrongValuesStatsSyncManualBoundedGuavaTest
          - strongKeysAndStrongValuesAsyncLoadingBoundedCaffeineTest
          - strongKeysAndSoftValuesSyncManualBoundedCaffeineSlowTest
          - strongKeysAndSoftValuesSyncLoadingUnboundedGuavaSlowTest
          - strongKeysAndSoftValuesStatsSyncManualUnboundedGuavaTest
          - weakKeysAndWeakValuesSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndWeakValuesStatsSyncManualBoundedCaffeineTest
          - weakKeysAndWeakValuesStatsSyncLoadingUnboundedGuavaTest
          - weakKeysAndStrongValuesSyncManualUnboundedGuavaSlowTest
          - weakKeysAndStrongValuesSyncLoadingUnboundedCaffeineTest
          - weakKeysAndStrongValuesStatsSyncLoadingBoundedGuavaTest
          - weakKeysAndStrongValuesAsyncManualUnboundedCaffeineTest
          - weakKeysAndSoftValuesSyncLoadingBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesStatsSyncManualBoundedCaffeineTest
          - weakKeysAndSoftValuesStatsSyncLoadingUnboundedGuavaTest
          - strongKeysAndWeakValuesSyncManualUnboundedGuavaSlowTest
          - strongKeysAndWeakValuesSyncLoadingUnboundedCaffeineTest
          - strongKeysAndWeakValuesStatsSyncLoadingBoundedGuavaTest
          - strongKeysAndStrongValuesSyncLoadingBoundedCaffeineTest
          - strongKeysAndStrongValuesAsyncManualBoundedCaffeineTest
          - strongKeysAndSoftValuesSyncManualUnboundedGuavaSlowTest
          - strongKeysAndSoftValuesSyncLoadingUnboundedCaffeineTest
          - strongKeysAndSoftValuesStatsSyncLoadingBoundedGuavaTest
          - weakKeysAndWeakValuesSyncManualBoundedCaffeineSlowTest
          - weakKeysAndWeakValuesSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncManualUnboundedGuavaTest
          - weakKeysAndStrongValuesSyncManualUnboundedCaffeineTest
          - weakKeysAndStrongValuesSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndStrongValuesStatsSyncManualBoundedGuavaTest
          - weakKeysAndStrongValuesAsyncLoadingBoundedCaffeineTest
          - weakKeysAndSoftValuesSyncManualBoundedCaffeineSlowTest
          - weakKeysAndSoftValuesSyncLoadingUnboundedGuavaSlowTest
          - weakKeysAndSoftValuesStatsSyncManualUnboundedGuavaTest
          - strongKeysAndWeakValuesSyncManualUnboundedCaffeineTest
          - strongKeysAndWeakValuesSyncLoadingBoundedGuavaSlowTest
          - strongKeysAndWeakValuesStatsSyncManualBoundedGuavaTest
          - strongKeysAndStrongValuesSyncManualBoundedCaffeineTest
          - strongKeysAndStrongValuesSyncLoadingUnboundedGuavaTest
          - strongKeysAndSoftValuesSyncManualUnboundedCaffeineTest
          - strongKeysAndSoftValuesSyncLoadingBoundedGuavaSlowTest
          - strongKeysAndSoftValuesStatsSyncManualBoundedGuavaTest
          - weakKeysAndWeakValuesSyncManualUnboundedGuavaSlowTest
          - weakKeysAndWeakValuesSyncLoadingUnboundedCaffeineTest
          - weakKeysAndWeakValuesStatsSyncLoadingBoundedGuavaTest
          - weakKeysAndStrongValuesSyncManualBoundedGuavaSlowTest
          - weakKeysAndStrongValuesSyncLoadingBoundedCaffeineTest
          - weakKeysAndStrongValuesAsyncManualBoundedCaffeineTest
          - weakKeysAndSoftValuesSyncManualUnboundedGuavaSlowTest
          - weakKeysAndSoftValuesSyncLoadingUnboundedCaffeineTest
          - weakKeysAndSoftValuesStatsSyncLoadingBoundedGuavaTest
          - strongKeysAndWeakValuesSyncManualBoundedGuavaSlowTest
          - strongKeysAndWeakValuesSyncLoadingBoundedCaffeineTest
          - strongKeysAndStrongValuesSyncManualUnboundedGuavaTest
          - strongKeysAndSoftValuesSyncManualBoundedGuavaSlowTest
          - strongKeysAndSoftValuesSyncLoadingBoundedCaffeineTest
          - weakKeysAndWeakValuesSyncManualUnboundedCaffeineTest
          - weakKeysAndWeakValuesSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndWeakValuesStatsSyncManualBoundedGuavaTest
          - weakKeysAndStrongValuesSyncManualBoundedCaffeineTest
          - weakKeysAndStrongValuesSyncLoadingUnboundedGuavaTest
          - weakKeysAndSoftValuesSyncManualUnboundedCaffeineTest
          - weakKeysAndSoftValuesSyncLoadingBoundedGuavaSlowTest
          - weakKeysAndSoftValuesStatsSyncManualBoundedGuavaTest
          - strongKeysAndWeakValuesSyncManualBoundedCaffeineTest
          - strongKeysAndWeakValuesSyncLoadingUnboundedGuavaTest
          - strongKeysAndStrongValuesSyncLoadingBoundedGuavaTest
          - strongKeysAndSoftValuesSyncManualBoundedCaffeineTest
          - strongKeysAndSoftValuesSyncLoadingUnboundedGuavaTest
          - weakKeysAndWeakValuesSyncManualBoundedGuavaSlowTest
          - weakKeysAndWeakValuesSyncLoadingBoundedCaffeineTest
          - weakKeysAndStrongValuesSyncManualUnboundedGuavaTest
          - weakKeysAndSoftValuesSyncManualBoundedGuavaSlowTest
          - weakKeysAndSoftValuesSyncLoadingBoundedCaffeineTest
          - strongKeysAndWeakValuesSyncManualUnboundedGuavaTest
          - strongKeysAndStrongValuesSyncManualBoundedGuavaTest
          - strongKeysAndSoftValuesSyncManualUnboundedGuavaTest
          - weakKeysAndWeakValuesSyncManualBoundedCaffeineTest
          - weakKeysAndWeakValuesSyncLoadingUnboundedGuavaTest
          - weakKeysAndStrongValuesSyncLoadingBoundedGuavaTest
          - weakKeysAndSoftValuesSyncManualBoundedCaffeineTest
          - weakKeysAndSoftValuesSyncLoadingUnboundedGuavaTest
          - strongKeysAndWeakValuesSyncLoadingBoundedGuavaTest
          - strongKeysAndSoftValuesSyncLoadingBoundedGuavaTest
          - weakKeysAndWeakValuesSyncManualUnboundedGuavaTest
          - weakKeysAndStrongValuesSyncManualBoundedGuavaTest
          - weakKeysAndSoftValuesSyncManualUnboundedGuavaTest
          - strongKeysAndWeakValuesSyncManualBoundedGuavaTest
          - strongKeysAndSoftValuesSyncManualBoundedGuavaTest
          - weakKeysAndWeakValuesSyncLoadingBoundedGuavaTest
          - weakKeysAndSoftValuesSyncLoadingBoundedGuavaTest
          - weakKeysAndWeakValuesSyncManualBoundedGuavaTest
          - weakKeysAndSoftValuesSyncManualBoundedGuavaTest
          - caffeine:eclipseTest
          - caffeine:jctoolsTest
          - caffeine:openjdkTest
          - caffeine:apacheTest
          - caffeine:googleTest
          - caffeine:jsr166Test
          - caffeine:moduleTest
          - caffeine:osgiTest
          - caffeine:test
          - simulator:check
          - jcache:check
          - guava:check
    env:
      JAVA_VERSION: 25
      JAVA_TEST_VERSION: 26
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@95d9a5deda9de15063e7595e9719c11c38c90ae2 # v2.13.2
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: ${{ env.ALLOWED_ENDPOINTS }}
      - name: Checkout
        uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      - name: Setup Gradle
        uses: ./.github/actions/run-gradle
        with:
          java: ${{ env.JAVA_TEST_VERSION }}-ea
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}
      - name: Run Tests
        env:
          TEST_SUITE: ${{ matrix.suite }}
        run: >
          ./gradlew -PearlyAccess=true -Dscan.tag.${GITHUB_WORKFLOW// /_}
          -PjavaTestVersion="$JAVA_TEST_VERSION" "$TEST_SUITE"
