name: Trivy Vulnerability Scanner
permissions: {}
on: [ push, pull_request, workflow_dispatch ]
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  trivy:
    name: Trivy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write # Needed to annotate commit
      actions: read # Needed for uploading security scan results
      security-events: write # Needed for uploading security scan results
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@bf7454d06d71f1098171f2acdf0cd4708d7b5920 # v2.20.0
        with:
          disable-sudo-and-containers: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            get.trivy.dev:443
            ghcr.io:443
            github.com:443
            mirror.gcr.io:443
            objects.githubusercontent.com:443
            pkg-containers.githubusercontent.com:443
            release-assets.githubusercontent.com:443
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@ed142fd0673e97e23eac54620cfb913e5ce36c25 # v0.36.0
        continue-on-error: true
        with:
          scan-type: fs
          format: sarif
          output: results.sarif
      - name: Check file existence
        id: check_files
        uses: andstor/file-existence-action@558493d6c74bf472d87c84eab196434afc2fa029 # v3.1.0
        with:
          files: results.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@54f647b7e1bb85c95cddabcd46b0c578ec92bc1a # v4.36.3
        if: steps.check_files.outputs.files_exists == 'true'
        with:
            sarif_file: results.sarif
